<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="ProcessItmID" targetNamespace="http://xmlns.oracle.com/UPCConversion/UniversalItemID/ProcessItmID" xmlns:client="http://xmlns.oracle.com/UPCConversion/UniversalItemID/ProcessItmID" xmlns:ns1="http://xmlns.oracle.com/UPCConversion/UniversalItemID/ProcessItmID" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID!5.5/ProcessItmID.wsdl</abstractWSDL>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="ProcessItmIDBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
    <plnk:partnerLinkType name="ProcessItmID">
        <plnk:role name="ProcessItmIDProvider" portType="client:ProcessItmID"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.oracle.com/UPCConversion/UniversalItemID/ProcessItmID" schemaLocation="ProcessItmID.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.oracle.com/UPCConversion/UniversalItemID/ProcessItmID" schemaLocation="ProcessItmID.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ProcessItmIDRequestMessage">
        <wsdl:part element="client:process" name="payload"/>
    </wsdl:message>
    <wsdl:message name="ProcessItmIDResponseMessage">
        <wsdl:part element="client:processResponse" name="payload"/>
    </wsdl:message>
    <wsdl:portType name="ProcessItmID">
        <wsdl:operation name="process">
            <wsdl:input message="client:ProcessItmIDRequestMessage"/>
            <wsdl:output message="client:ProcessItmIDResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ProcessItmIDBinding" type="client:ProcessItmID">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation soapAction="process" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="processitmid_client_ep">
        <wsdl:port binding="client:ProcessItmIDBinding" name="ProcessItmID_pt">
            <soap:address location="http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID/processitmid_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>