<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns3="http://www.xmlsn.saksinc.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ns0="http://xmlns.saksinc.com/CommonModules/LookupFindIt/Types" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:client="http://xmlns.saksinc.com/CommonModules/FinditSearch/LookupFindIt" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns2="http://www.xmlns.saksinc.com" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://xmlns.saksinc.com/CommonModules/LookupFindIt" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns3 wsdl ns0 client plnk ns2 xsd ns1 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
   <xsl:template match="/">
      <ns2:WhereClauseString>
         <ns2:WhereClause>
            <xsl:value-of select="concat(/ns2:WhereClause/ns2:Chain,/ns2:WhereClause/ns2:CountryCode,/ns2:WhereClause/ns2:DeptNo,/ns2:WhereClause/ns2:ClassNo,/ns2:WhereClause/ns2:SSN,/ns2:WhereClause/ns2:VendorStyle,/ns2:WhereClause/ns2:MfgName,/ns2:WhereClause/ns2:MfgNo,/ns2:WhereClause/ns2:GMMNo,/ns2:WhereClause/ns2:DMMNo,/ns2:WhereClause/ns2:UdaID,/ns2:WhereClause/ns2:UdaValue)"/>
         </ns2:WhereClause>
      </ns2:WhereClauseString>
   </xsl:template>
</xsl:stylesheet>