<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RetrieveInfoBySSN" targetNamespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveInfoBySSN" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveInfoBySSN" xmlns:ns1="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveInfoBySSN" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
    <abstractWSDL>http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID!5.5/RetrieveInfoBySSN.wsdl</abstractWSDL>
  </wsdl:documentation>
  <plnk:partnerLinkType name="RetrieveInfoBySSN">
    <plnk:role name="RetrieveInfoBySSNProvider" portType="client:RetrieveInfoBySSN"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveInfoBySSN" schemaLocation="retrieveInfoBySSN_ep.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="RetrieveInfoBySSNRequestMessage">
    <wsdl:part name="payload" element="client:RetrieveInfoBySSNRequest"/>
  </wsdl:message>
  <wsdl:message name="RetrieveInfoBySSNResponseMessage">
    <wsdl:part name="payload" element="client:RetrieveInfoBySSNResponse"/>
  </wsdl:message>
  <wsdl:message name="FaultMessageRetrieveBySSN">
    <wsdl:part name="part" element="client:RetrieveInfoBySSNFault"/>
  </wsdl:message>
  <wsdl:portType name="RetrieveInfoBySSN">
    <wsdl:operation name="retrieveInfoBySSN">
      <wsdl:input message="client:RetrieveInfoBySSNRequestMessage"/>
      <wsdl:output message="client:RetrieveInfoBySSNResponseMessage"/>
      <wsdl:fault name="part" message="client:FaultMessageRetrieveBySSN"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RetrieveInfoBySSNBinding" type="client:RetrieveInfoBySSN">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="retrieveInfoBySSN">
      <soap:operation style="document" soapAction="retrieveInfoBySSN"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="part">
        <soap:fault name="part" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="retrieveInfoBySSN_ep">
    <wsdl:port name="RetrieveInfoBySSN_pt" binding="client:RetrieveInfoBySSNBinding">
      <soap:address location="http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID/retrieveInfoBySSN_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>