<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="RetrieveByIDandChain" targetNamespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveByIDandChain" xmlns:client="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveByIDandChain" xmlns:ns1="http://xmlns.saksinc.com/CommonModules/UniversalItemID/Types" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID!5.5/RetrieveByIDandChain.wsdl</abstractWSDL>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="RetrieveByIDandChainBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
    <plnk:partnerLinkType name="RetrieveByIDandChain">
        <plnk:role name="RetrieveByIDandChainProvider" portType="client:RetrieveByIDandChain"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveByIDandChain" schemaLocation="RetrieveByIDandChain.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/Types" schemaLocation="UniversalItemIDTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="RetrieveByIDandChainRequestMessage">
        <wsdl:part element="client:RetrieveByIDandChainRequest" name="payload"/>
    </wsdl:message>
    <wsdl:message name="RetrieveByIDandChainResponseMessage">
        <wsdl:part element="client:RetrieveByIDandChainResponse" name="payload"/>
    </wsdl:message>
    <wsdl:message name="FaultMessageRetrieveByIDandChain">
        <wsdl:part element="client:RetrieveByIDandChainFault" name="part"/>
    </wsdl:message>
    <wsdl:portType name="RetrieveByIDandChain">
        <wsdl:operation name="retrieveByIDandChain">
            <wsdl:input message="client:RetrieveByIDandChainRequestMessage"/>
            <wsdl:output message="client:RetrieveByIDandChainResponseMessage"/>
            <wsdl:fault message="client:FaultMessageRetrieveByIDandChain" name="part"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RetrieveByIDandChainBinding" type="client:RetrieveByIDandChain">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="retrieveByIDandChain">
            <soap:operation soapAction="retrieveByIDandChain" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="part">
                <soap:fault name="part" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RetrieveByIDandChainService_ep">
        <wsdl:port binding="client:RetrieveByIDandChainBinding" name="RetrieveByIDandChain_pt">
            <soap:address location="http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID/RetrieveByIDandChainService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>