<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="RetrieveByDeptClass" targetNamespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveByDeptClass" xmlns:client="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveByDeptClass" xmlns:ns1="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveByIDandChain" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID!5.5/RetrieveByDeptClass.wsdl</abstractWSDL>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="RetrieveByDeptClassBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
    <plnk:partnerLinkType name="RetrieveByDeptClass">
        <plnk:role name="RetrieveByDeptClassProvider" portType="client:RetrieveByDeptClass"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveByIDandChain" schemaLocation="RetrieveByDeptClass.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="RetrieveByDeptClassRequestMessage">
        <wsdl:part element="ns1:RetrieveByDeptClassRequest" name="payload"/>
    </wsdl:message>
    <wsdl:message name="RetrieveByDeptClassResponseMessage">
        <wsdl:part element="ns1:RetrieveByDeptClassResponse" name="payload"/>
    </wsdl:message>
    <wsdl:message name="FaultMessageRetrieveByDeptClass">
        <wsdl:part element="ns1:RetrieveByDeptClassFault" name="part"/>
    </wsdl:message>
    <wsdl:portType name="RetrieveByDeptClass">
        <wsdl:operation name="retrieveByDeptClass">
            <wsdl:input message="client:RetrieveByDeptClassRequestMessage"/>
            <wsdl:output message="client:RetrieveByDeptClassResponseMessage"/>
            <wsdl:fault message="client:FaultMessageRetrieveByDeptClass" name="FaultMessageRetrieveByDeptClass"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RetrieveByDeptClassBinding" type="client:RetrieveByDeptClass">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="retrieveByDeptClass">
            <soap:operation soapAction="retrieveByDeptClass" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="FaultMessageRetrieveByDeptClass">
                <soap:fault name="FaultMessageRetrieveByDeptClass" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RetrieveByDeptClassService_ep">
        <wsdl:port binding="client:RetrieveByDeptClassBinding" name="RetrieveByDeptClass_pt">
            <soap:address location="http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID/RetrieveByDeptClassService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>