<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="RetrieveInfoBySKN" targetNamespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveInfoBySKN" xmlns:client="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveInfoBySKN" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID!5.5/RetrieveInfoBySKN.wsdl</abstractWSDL>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="RetrieveInfoBySKNBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
    <plnk:partnerLinkType name="RetrieveInfoBySKN">
        <plnk:role name="RetrieveInfoBySKNProvider" portType="client:RetrieveInfoBySKN"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.saksinc.com/CommonModules/UniversalItemID/RetrieveInfoBySKN" schemaLocation="RetrieveInfoBySKN.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="RetrieveInfoBySKNRequestMessage">
        <wsdl:part element="client:RetrieveInfoBySKNRequest" name="payload"/>
    </wsdl:message>
    <wsdl:message name="RetrieveInfoBySKNResponseMessage">
        <wsdl:part element="client:RetrieveInfoBySKNResponse" name="payload"/>
    </wsdl:message>
    <wsdl:message name="FaultMessageRetrieveBySKN">
        <wsdl:part element="client:RetrieveInfoBySKNFault" name="part"/>
    </wsdl:message>
    <wsdl:portType name="RetrieveInfoBySKN">
        <wsdl:operation name="retrieveInfoBySKN">
            <wsdl:input message="client:RetrieveInfoBySKNRequestMessage"/>
            <wsdl:output message="client:RetrieveInfoBySKNResponseMessage"/>
            <wsdl:fault message="client:FaultMessageRetrieveBySKN" name="part"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RetrieveInfoBySKNBinding" type="client:RetrieveInfoBySKN">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="retrieveInfoBySKN">
            <soap:operation soapAction="retrieveInfoBySKN" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="part">
                <soap:fault name="part" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RetrieveInfoBySKNService_ep">
        <wsdl:port binding="client:RetrieveInfoBySKNBinding" name="RetrieveInfoBySKN_pt">
            <soap:address location="http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/UniversalItemID/RetrieveInfoBySKNService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>