<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="LookupFindIt" targetNamespace="http://xmlns.saksinc.com/CommonModules/FinditSearch/LookupFindIt" xmlns:client="http://xmlns.saksinc.com/CommonModules/FinditSearch/LookupFindIt" xmlns:ns1="http://xmlns.saksinc.com/CommonModules/LookupFindIt" xmlns:ns2="http://www.xmlns.saksinc.com" xmlns:ns3="http://www.xmlsn.saksinc.com" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/FinditSearch!2.0/LookupFindIt.wsdl</abstractWSDL>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="LookupFindItBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
    <plnk:partnerLinkType name="LookupFindIt">
        <plnk:role name="LookupFindItProvider" portType="client:LookupFindIt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.saksinc.com/CommonModules/LookupFindIt" schemaLocation="LookupFindIt.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                    </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                    </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                    </xsd:schema>
    </wsdl:types>
    <wsdl:message name="LookupFindItRequestMessage">
        <wsdl:part element="ns1:FindItRequest" name="payload"/>
    </wsdl:message>
    <wsdl:message name="LookupFindItResponseMessage">
        <wsdl:part element="ns1:FindItResponse" name="payload"/>
    </wsdl:message>
    <wsdl:portType name="LookupFindIt">
        <wsdl:operation name="process">
            <wsdl:input message="client:LookupFindItRequestMessage"/>
            <wsdl:output message="client:LookupFindItResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="LookupFindItBinding" type="client:LookupFindIt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation soapAction="process" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="LookupFindIt_ep">
        <wsdl:port binding="client:LookupFindItBinding" name="LookupFindIt_pt">
            <soap:address location="http://jxn-ux-fusion11q.saksinc.com:8001/soa-infra/services/CommonModules/FinditSearch/LookupFindIt_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>